### ISSUE TITLE
Suggest adding Google Fonts guide for using type in AR/VR

### ISSUE THREAD

**Issue by rubychen** [jackyangzzh/XR-Design-Handbook#1]
Thank you for creating this repository!

I'd like to suggest adding Google Fonts guide for using type in AR/VR
https://fonts.google.com/knowledge/using_type_in_ar_and_vr

**Comment by rubychen** [comment]
one more! Ali's guide is also a huge knowledge dump resource for me: https://aliheston.gitbook.io/the-design-of-virtual-and-augmented-reality/
highly recommended!

**Comment by jackyangzzh** [comment]
@rubychen  Thank you so much for the recommendations! I finally got some time today and added both resources you mentioned in Commit https://github.com/jackyangzzh/XR-Design-Handbook/commit/43c24e0c74bfa128b121e84da85f1902ad81137f
